Fixed account page error:
TypeError: Cannot use 'in' operator to search for 'public' in null
Changes to be committed:
	modified:   src/views/account/AccountView/Profile.js